name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: |
        cd Backend
        php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: |
        cd Backend
        composer install
    - name: Generate key
      run: |
        cd Backend
        php artisan key:generate
    - name: Directory Permissions
      run: |
        cd Backend
        chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        cd Backend
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        cd Backend
        vendor/bin/phpunit
